version: "3.8"

services:

  metrics-scraper:
    image: ghcr.io/acornsoftlab/kore-board.metrics-scraper:latest
    command: --kubeconfig=/app/.kube/config --db-file=/app/data/metrics.db --log-level=info
    volumes:
      - kubeconfig:/app/.kube
      - data:/app/data

  backend:
    image: ghcr.io/acornsoftlab/kore-board.backend:latest
    privileged: true
    command: >-
      --kubeconfig=/app/.kube/config --metrics-scraper-url=http://metrics-scraper:8000 --log-level=info
    volumes:
      - kubeconfig:/app/.kube
    links:
      - metrics-scraper

  frontend:
    image: ghcr.io/acornsoftlab/kore-board.frontend:latest
    ports:
      - 3000:80
    links:
      - backend

volumes:
  data: {}
  kubeconfig: {}
