kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ .Chart.Name }}
    kore.board: metrics-scraper
  name: metrics-scraper
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: {{ .Chart.Name }}
    kore.board: metrics-scraper

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: {{ .Chart.Name }}
    kore.board: metrics-scraper
  name: metrics-scraper
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      kore.board: metrics-scraper
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        kore.board: metrics-scraper
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
    spec:
      containers:
        - name: metrics-scraper
          image: ghcr.io/kore3lab/kore-board.metrics-scraper:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --kubeconfig=/app/.kube/config
            - --log-level=info
            - --db-file=/app/data/metrics.db
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - mountPath: /app/.kube
              name: kubeconfig
            - mountPath: /app/data
              name: data-volume
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 2001
      volumes:
        - name: kubeconfig
          configMap:
            name: kore-board-kubeconfig
        - name: data-volume
      {{- if .Values.metricsScraper.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default "kore-board-metrics-scraper" .Values.metricsScraper.persistence.existingClaim  }}
      {{- else }}
          emptyDir: {}
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}
      nodeSelector:
        "kubernetes.io/os": linux