kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ .Chart.Name }}
    kore.board: backend
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: {{ .Chart.Name }}
    kore.board: backend

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: {{ .Chart.Name }}
    kore.board: backend
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      kore.board: backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        kore.board: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/kore3lab/kore-board.backend:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --kubeconfig=strategy=configmap,configmap={{ .Chart.Name }}-kubeconfig,namespace={{ .Release.Namespace }},filename=config
            - --metrics-scraper-url=http://metrics-scraper:8000
            - --terminal-url=http://terminal:3003
            - --log-level=info
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}
      serviceAccountName: {{ .Chart.Name }}
      nodeSelector:
        "kubernetes.io/os": linux
