version: "3.8"

services:

  metrics-scraper:
    image: ghcr.io/acornsoftlab/kore-board.metrics-scraper:latest
    command: --kubeconfig=/app/.kube/config --db-file=/app/data/metrics.db --log-level=info
    volumes:
      - "${KUBECONFIG}:/app/.kube/config"
      - data:/app/data

  backend:
    image: ghcr.io/acornsoftlab/kore-board.backend:latest
    command: >-
      --kubeconfig=/app/.kube/config --metrics-scraper-url=http://metrics-scraper:8000 --log-level=info --auth='{"strategy":"cookie", "secret": {"type": "static-user", "username": "admin", "password": "acornsoft"} }'
    volumes:
      - "${KUBECONFIG}:/app/.kube/config"
    links:
      - metrics-scraper

  frontend:
    image: ghcr.io/acornsoftlab/kore-board.frontend:latest
    ports:
      - 3000:80
    volumes:
      - data:/tmp
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - backend

volumes:
  data: {}
