apiVersion: v1
kind: Namespace
metadata:
  name: kore

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kore-board
  name: kore-board
  namespace: kore

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-kore-board
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kore-board
  namespace: kore

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kore-board
    acornsoft.dashboard: metrics-scraper
  name: metrics-scraper
  namespace: kore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kore-board
      acornsoft.dashboard: metrics-scraper
  template:
    metadata:
      labels:
        app: kore-board
        acornsoft.dashboard: metrics-scraper
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
    spec:
      containers:
        - name: metrics-scraper
          image: ghcr.io/acornsoftlab/kore-board.metrics-scraper:latest
          imagePullPolicy: Always
          args:
            - --kubeconfig=/app/.kube/config
            - --log-level=info
          ports:
            - containerPort: 8000
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              scheme: HTTP
#              path: /
#              port: 8000
#            initialDelaySeconds: 30
#            timeoutSeconds: 30
          volumeMounts:
            - mountPath: /app/.kube
              name: dashboard-kubeconfig
            - mountPath: /tmp
              name: tmp-volume
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 2001
      volumes:
        - name: dashboard-kubeconfig
          configMap:
            name: kore-board-kubeconfig
        - name: tmp-volume
          emptyDir: {}
      serviceAccountName: kore-board
      nodeSelector:
        "kubernetes.io/os": linux


---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kore-board
    acornsoft.dashboard: backend
  name: backend
  namespace: kore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kore-board
      acornsoft.dashboard: backend
  template:
    metadata:
      labels:
        app: kore-board
        acornsoft.dashboard: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/acornsoftlab/kore-board.backend:latest
          imagePullPolicy: Always
          args:
            - --kubeconfig=/app/.kube/config
            - --log-level=info
            - --metrics-scraper-url=http://metrics-scraper:8000
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
          - mountPath: /app/.kube
            name: dashboard-kubeconfig
          - mountPath: /tmp
            name: tmp-volume
      volumes:
        - name: dashboard-kubeconfig
          configMap:
            name: kore-board-kubeconfig
        - name: tmp-volume
          emptyDir: {}
      serviceAccountName: kore-board
      nodeSelector:
        "kubernetes.io/os": linux


---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kore-board
    acornsoft.dashboard: frontend
  name: frontend
  namespace: kore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kore-board
      acornsoft.dashboard: frontend
  template:
    metadata:
      labels:
        app: kore-board
        acornsoft.dashboard: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/acornsoftlab/kore-board.frontend:latest
          imagePullPolicy: Always
          env:
          - name: BACKEND_PORT
            value: "30081"
          ports:
            - containerPort: 3001
              protocol: TCP
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
        - name: tmp-volume
          emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: kore-board
    acornsoft.dashboard: frontend
  name: frontend
  namespace: kore
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30080
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: kore-board
    acornsoft.dashboard: frontend

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: kore-board
    acornsoft.dashboard: backend
  name: backend
  namespace: kore
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30081
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: kore-board
    acornsoft.dashboard: backend

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: kore-board
    acornsoft.dashboard: metrics-scraper
  name: metrics-scraper
  namespace: kore
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: kore-board
    acornsoft.dashboard: metrics-scraper
